[package]
name = "simple-server-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
clap = { version = "4.5.4", features = ["derive"] }
mcp-sdk = { path = "../.." }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
