[package]
name = "simple-server-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1"
mcp-sdk = { path = "../.." }
serde_json = "1.0"
tokio = { version = "1", features = ["full"] }
# The 'clap' dependency has been removed.
